/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    applications: Application;
    distributors: Distributor;
    news: News;
    pages: Page;
    faqs: Faq;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    distributors: DistributorsSelect<false> | DistributorsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'zh-tw') | ('en' | 'zh-tw')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'zh-tw';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  _order?: string | null;
  /**
   * 型號，例如 MT-A110、MT-A310H、MT-A710
   */
  model: string;
  /**
   * URL slug，例如 mt-a110
   */
  slug: string;
  /**
   * 產品顯示名稱，例如 Pneumatic Score Cut Knife Holder
   */
  title: string;
  productType: 'knife-holder' | 'knife' | 'guide-bar' | 'accessory';
  /**
   * 刀組必填；刀片/導桿/配件可留空
   */
  cuttingMethod?: ('score-cut' | 'shear-cut' | 'half-cut' | 'hot-cut') | null;
  /**
   * 型號家族分級：Score 輕型 / 中型（A110/A130/A160/B110/C121）vs 重磅型（A140/A170/A510）；Shear 精密型（A410/A450）vs 通用型（A650/A850/A880）
   */
  familyTier?:
    ('light-duty' | 'medium-duty' | 'heavy-duty' | 'precision' | 'general' | 'medical' | 'heat-sealed') | null;
  /**
   * 一句話賣點，顯示於產品卡
   */
  tagline?: string | null;
  /**
   * 建議採 slittec 三段式結構：技術特點 → 解決什麼問題 → 適用材料
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 規格標示原則：雙值標示（standard 為保守值、max 為極限值 + 條件註記），避免保守值被拿去比對手極限值
   */
  keySpecs?: {
    minSlitWidth?: {
      /**
       * 例如 < 25mm
       */
      standard?: string | null;
      /**
       * 例如 < 13mm
       */
      max?: string | null;
      /**
       * 極限值的條件註記，例如「特定材料 / 特殊刀片」
       */
      condition?: string | null;
    };
    maxSpeed?: {
      /**
       * 例如 20 m/min
       */
      standard?: string | null;
      /**
       * 例如 30 m/min
       */
      max?: string | null;
      condition?: string | null;
    };
    /**
     * 例如 3–6 kg/cm²
     */
    airPressure?: string | null;
    /**
     * 例如 ±0.005mm
     */
    tolerance?: string | null;
    maxTemperature?: {
      /**
       * 例如 600°C
       */
      standard?: string | null;
      /**
       * 例如 650°C
       */
      max?: string | null;
      condition?: string | null;
    };
  };
  detailedSpecs?:
    | {
        label: string;
        value: string;
        /**
         * 條件註記（up to / max. 標示原則）
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 對應第六章產業分類矩陣（此型號適用的產業/材料分類）
   */
  applications?: (number | Application)[] | null;
  images?: (number | Media)[] | null;
  /**
   * PDF 型錄下載
   */
  pdfCatalog?: (number | null) | Media;
  /**
   * 產品頁 Overview 的交錯圖文區塊，建議 3–6 個（奇偶交錯排版）
   */
  featureHighlights?:
    | {
        image?: (number | null) | Media;
        /**
         * 例如 Patented Design — One Step Ahead
         */
        heading: string;
        /**
         * 2–3 句說明
         */
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 產品頁 Drawings tab 顯示，前台帶浮水印與防下載
   */
  technicalDrawings?: (number | Media)[] | null;
  /**
   * 工程圖適用版本或尺寸備註
   */
  drawingNotes?: string | null;
  /**
   * 產品頁 3D View tab 顯示，透過 API 代理存取不暴露直接 URL
   */
  model3d?: (number | null) | Media;
  relatedProducts?: (number | Product)[] | null;
  /**
   * 顯示於首頁產品分類快速入口
   */
  featured?: boolean | null;
  /**
   * 同分類內排序，數字小在前（保留給特殊置頂用；一般拖曳排序即可）
   */
  displayOrder?: number | null;
  /**
   * 每頁獨立的 SEO 設定；留空時前台使用預設值
   */
  seo?: {
    /**
     * 建議 50–60 字元，包含目標關鍵字
     */
    metaTitle?: string | null;
    /**
     * 建議 140–160 字元，避免與其他頁面重複
     */
    metaDescription?: string | null;
    /**
     * 社群分享縮圖（1200×630）
     */
    ogImage?: (number | null) | Media;
    /**
     * 勾選後此頁不被搜尋引擎索引
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  /**
   * 第六章矩陣編號 1–9，也作為頁面排序
   */
  categoryNumber: number;
  /**
   * 例如 Paper & Board、Plastic Film
   */
  title: string;
  /**
   * 例如 paper-board、plastic-film、metal-foils
   */
  slug: string;
  coverage?:
    | {
        /**
         * 例如 牛皮紙 Kraft Paper、銅箔 Copper Foil
         */
        material: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 此分類適用的切割方式（矩陣「切割方式」欄）
   */
  cuttingMethods: ('score-cut' | 'shear-cut' | 'half-cut' | 'hot-cut')[];
  /**
   * 敘事開頭：此產業的切割痛點（例如不織布的粉塵、毛絮、脫紗）
   */
  painPoints?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 例如不織布：Score 窄幅經濟 / Shear 高速高品質低粉塵 / Hot 化纖熔封
   */
  selectionLogic?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 矩陣「對應刀組」欄，例如紙類：Score → A110/A130/A160；Shear → A650/A850/A880
   */
  productRecommendations?:
    | {
        cuttingMethod: 'score-cut' | 'shear-cut' | 'half-cut' | 'hot-cut';
        products: (number | Product)[];
        /**
         * 補充說明，例如「重磅材料建議 A510/A170」
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 互動選型工具資料來源：符合材料 + 厚度區間時推薦對應型號
   */
  selectorRules?:
    | {
        /**
         * 選型器顯示的材料選項，例如 PE Film、Copper Foil
         */
        materialLabel: string;
        /**
         * 最小厚度（µm），留空表示不限
         */
        thicknessMin?: number | null;
        /**
         * 最大厚度（µm），留空表示不限
         */
        thicknessMax?: number | null;
        recommendedProducts: (number | Product)[];
        /**
         * 推薦理由，顯示於選型結果
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  /**
   * 每頁獨立的 SEO 設定；留空時前台使用預設值
   */
  seo?: {
    /**
     * 建議 50–60 字元，包含目標關鍵字
     */
    metaTitle?: string | null;
    /**
     * 建議 140–160 字元，避免與其他頁面重複
     */
    metaDescription?: string | null;
    /**
     * 社群分享縮圖（1200×630）
     */
    ogImage?: (number | null) | Media;
    /**
     * 勾選後此頁不被搜尋引擎索引
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 圖片替代文字（SEO / 無障礙）
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors".
 */
export interface Distributor {
  id: number;
  companyName: string;
  /**
   * ISO 3166-1 alpha-2 國碼（大寫），例如 TW、DE、IN、VN——互動地圖以此比對
   */
  countryCode: string;
  /**
   * 國家顯示名稱，例如 Germany / 德國
   */
  countryName: string;
  region: 'asia-pacific' | 'europe' | 'north-america' | 'latin-america' | 'middle-east-africa';
  /**
   * 服務範圍備註，例如「僅北印度」「含鄰近三國」
   */
  coverageNote?: string | null;
  contact?: {
    person?: string | null;
    email?: string | null;
    phone?: string | null;
    website?: string | null;
    address?: string | null;
  };
  logo?: (number | null) | Media;
  /**
   * 取消勾選時，地圖只顯示「本地區由代理商服務」並轉導詢價表單（由代理商轉介）
   */
  showContactPublicly?: boolean | null;
  /**
   * 停用後地圖視同無代理商地區（直接接單）
   */
  active?: boolean | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  category: 'exhibition' | 'product-news' | 'industry-knowledge' | 'company-news';
  publishedDate: string;
  /**
   * 列表頁摘要，建議 100–160 字元
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  /**
   * 文中提及的產品（新產品發佈時使用）
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * 每頁獨立的 SEO 設定；留空時前台使用預設值
   */
  seo?: {
    /**
     * 建議 50–60 字元，包含目標關鍵字
     */
    metaTitle?: string | null;
    /**
     * 建議 140–160 字元，避免與其他頁面重複
     */
    metaDescription?: string | null;
    /**
     * 社群分享縮圖（1200×630）
     */
    ogImage?: (number | null) | Media;
    /**
     * 勾選後此頁不被搜尋引擎索引
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * home / about / contact ...
   */
  slug: string;
  hero?: {
    /**
     * 例如 Precision Slitting Solutions — Made in Taiwan Since 1990
     */
    heading?: string | null;
    subheading?: string | null;
    image?: (number | null) | Media;
    /**
     * Hero 背景影片（mp4）。若同時提供 image，image 會作為 poster。
     */
    video?: (number | null) | Media;
    ctaLabel?: string | null;
    ctaLink?: string | null;
  };
  sections?:
    | (
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            heading?: string | null;
            items: {
              /**
               * 例如 35+、50+、±0.005mm
               */
              value: string;
              /**
               * 例如 Years of Precision、Countries Served
               */
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            milestones: {
              year: string;
              title: string;
              description?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            heading?: string | null;
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            /**
             * 站內路徑，例如 /contact
             */
            buttonLink: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * 每頁獨立的 SEO 設定；留空時前台使用預設值
   */
  seo?: {
    /**
     * 建議 50–60 字元，包含目標關鍵字
     */
    metaTitle?: string | null;
    /**
     * 建議 140–160 字元，避免與其他頁面重複
     */
    metaDescription?: string | null;
    /**
     * 社群分享縮圖（1200×630）
     */
    ogImage?: (number | null) | Media;
    /**
     * 勾選後此頁不被搜尋引擎索引
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * FAQ 顯示在哪個頁面（含 FAQPage JSON-LD）
   */
  page: 'products' | 'applications';
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'distributors';
        value: number | Distributor;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  _order?: T;
  model?: T;
  slug?: T;
  title?: T;
  productType?: T;
  cuttingMethod?: T;
  familyTier?: T;
  tagline?: T;
  description?: T;
  keySpecs?:
    | T
    | {
        minSlitWidth?:
          | T
          | {
              standard?: T;
              max?: T;
              condition?: T;
            };
        maxSpeed?:
          | T
          | {
              standard?: T;
              max?: T;
              condition?: T;
            };
        airPressure?: T;
        tolerance?: T;
        maxTemperature?:
          | T
          | {
              standard?: T;
              max?: T;
              condition?: T;
            };
      };
  detailedSpecs?:
    | T
    | {
        label?: T;
        value?: T;
        note?: T;
        id?: T;
      };
  applications?: T;
  images?: T;
  pdfCatalog?: T;
  featureHighlights?:
    | T
    | {
        image?: T;
        heading?: T;
        body?: T;
        id?: T;
      };
  technicalDrawings?: T;
  drawingNotes?: T;
  model3d?: T;
  relatedProducts?: T;
  featured?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  categoryNumber?: T;
  title?: T;
  slug?: T;
  coverage?:
    | T
    | {
        material?: T;
        id?: T;
      };
  cuttingMethods?: T;
  painPoints?: T;
  selectionLogic?: T;
  productRecommendations?:
    | T
    | {
        cuttingMethod?: T;
        products?: T;
        note?: T;
        id?: T;
      };
  selectorRules?:
    | T
    | {
        materialLabel?: T;
        thicknessMin?: T;
        thicknessMax?: T;
        recommendedProducts?: T;
        note?: T;
        id?: T;
      };
  heroImage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors_select".
 */
export interface DistributorsSelect<T extends boolean = true> {
  companyName?: T;
  countryCode?: T;
  countryName?: T;
  region?: T;
  coverageNote?: T;
  contact?:
    | T
    | {
        person?: T;
        email?: T;
        phone?: T;
        website?: T;
        address?: T;
      };
  logo?: T;
  showContactPublicly?: T;
  active?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedDate?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  relatedProducts?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        image?: T;
        video?: T;
        ctaLabel?: T;
        ctaLink?: T;
      };
  sections?:
    | T
    | {
        content?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              heading?: T;
              milestones?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  page?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}